version: "3.8"

services:
  llm_connector:
    image: usuario/llm_connector:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    ports:
      - "8001:8000"
    environment:
      - Gemini_API_KEY=${GEMINI_API_KEY}

  sklearn_model:
    image: usuario/sklearn_model:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    ports:
      - "8002:8000"

  cnn_image:
    image: usuario/cnn_image:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    ports:
      - "8003:8000"

  gradio_frontend:
    image: usuario/gradio_frontend:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "7860:7860"

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    command:
      - mlflow
      - server
      - --backend-store-uri
      - /mlflow/mlflow.db
      - --default-artifact-root
      - ./mlflow/artifacts
      - --host
      - 0.0.0.0
